# Generated by Django 4.1.3 on 2022-11-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtUser', models.CharField(max_length=30, verbose_name='NickName')),
                ('txtPass', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('txtUserType', models.CharField(choices=[('0', 'ADMINISTRADOR DEL SISTEMA'), ('1', 'GERENTE'), ('2', 'ADMINISTRATIVO'), ('3', 'RECURSOS HUMANOS'), ('4', 'VISITANTE')], max_length=1, verbose_name='Tipo de Usuario')),
                ('fhCreatedAt', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('bActive', models.BooleanField(default=False, verbose_name='Activo')),
                ('eIdPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Lista de Usuarios',
            },
        ),
    ]
