# Generated by Django 4.1.3 on 2022-11-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtName', models.CharField(max_length=30, verbose_name='Nombre(s)')),
                ('txtLastName', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('txtRFC', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('fhCreatedAt', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('bActive', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
